### ISSUE TITLE
Add Icons related to each service

### ISSUE THREAD

**Issue by AbdelrahmanBayoumi** [Seen-Arabic/Arabic-Services#14]

**Comment by AbdelrahmanBayoumi** [comment]
https://github.com/Seen-Arabic/Arabic-Services/commit/54e753fb3078c17d7b81b683951fec20c009d0cb

**Comment by YoussefMo7amed** [comment]
![image](https://github.com/Seen-Arabic/Arabic-Services/assets/39943970/d033f1fe-d36d-456e-b419-5e808a558473)
